"""
Django settings for PassMngSite project.

Generated by 'django-admin startproject' using Django 3.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'z&odmkebnw@z)y6!c9q0^9gvl8ngdvz^7hl^xcxw^t!z7+@!bd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [#add myapp here
    'django.contrib.admin',#admin
    'django.contrib.auth',#dastresi
    'django.contrib.contenttypes',
    'django.contrib.sessions',#modiriate session ha
    'django.contrib.messages',#payamhaye karnaran
    'django.contrib.staticfiles',#filhaye static ra dar yek makan jam mikonad.
    'PassMngSite.myapp', #ddm
    'django.contrib.sites', #ddm- estefade chand site as yek db-
    'django.contrib.flatpages',#ddm-manage static pages-table in db
    'bootstrap_modal_forms', #A Django plugin for creating AJAX driven forms in Bootstrap modal
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware', #marboot b admin bala
    'django.middleware.common.CommonMiddleware', #marboot b admin bala.
    'django.middleware.csrf.CsrfViewMiddleware', # method post and jologiri as csrf.
    'django.contrib.auth.middleware.AuthenticationMiddleware', #marboot b admin bala
    'django.contrib.messages.middleware.MessageMiddleware', #marboot b admin bala
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',#sites and flatpages
]

ROOT_URLCONF = 'PassMngSite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [(os.path.join(os.path.dirname(__file__),'templates'))], #added by ddm - in windows we use replace('\\','/')
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PassMngSite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

PASSWORD_HASHERS = [ #baad az nasbe django[argon2] ezafe mikonim.
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

SITE_ID = 1 # ddm--1 id site hast-->table: django_site//yani yek site darim


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/' #url static/just prefix
STATICFILES_DIR = [
    os.path.join(os.path.dirname(__file__),'static') #masire folder downloadi site for myapp- static files->js,img,css,...
]
STATIC_ROOT = os.path.join(BASE_DIR, 'JangoAssets') # all static files for projects into one file